CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       available_seats INTEGER NOT NULL,
                       cost_per100kmeur FLOAT(53) NOT NULL,
                       email VARCHAR(255),
                       flexibility_km FLOAT(53) NOT NULL,
                       flexibility_minutes INTEGER NOT NULL,
                       home_address VARCHAR(255),
                       name VARCHAR(255),
                       office_address VARCHAR(255),
                       password VARCHAR(255),
                       phone VARCHAR(255),
                       preferred_arrival_end TIME,
                       preferred_arrival_start TIME,
                       role VARCHAR(20) -- use DRIVER/PASSENGER as string
);
